theme: jekyll-theme-minimal
title: Docs from Prescription Free
description: Info related to learning web development and software engineering in the style of technical documentation.
github:
  is_user_page: false
  is_project_page: true
  owner_name: Prescription Free Academy (GitHub Organistion)
