theme: jekyll-theme-minimal
title: Academy Docs
description: Learning resources from the Prescription Free Academy.
github:
  is_user_page: false
  is_project_page: true
  owner_name: Prescription Free Academy (GitHub Organistion)
